apiVersion: gitops.podcd.io/v1
kind: Application
metadata:
  name: frontend
spec:
  image: docker.io/library/nginx@sha256:72ba65eb42c10344912a84ff42408db7d34f2feb642204570ab8fc5ffd29f1d3
  ports:
    - "8081:80" # shorthand for host 8081 -> container 80
  env:
    API_URL: http://127.0.0.1:8080
  healthcheck:
    tcp:
      port: 8081
---
apiVersion: gitops.podcd.io/v1
kind: Application
metadata:
  name: node-exporter
spec:
  image: quay.io/prometheus/node-exporter@sha256:1b4e4438faca4dd7e001dd445d161a4a2091b0fededa84093b3a8dfeae1f1be0
  ports:
    - host: 9100
      container: 9100
      hostIP: 127.0.0.1
  volumes:
    - source: /proc
      destination: /host/proc
      options: ro
  command: ["--path.procfs=/host/proc"]
  healthcheck:
    http:
      port: 9100
      path: /metrics
